name: Build & Push

on:
  push:
    branches: [ main ]


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: dcoker build . -t hk328/node_app_img
      - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - run: docker push hk328/node_app_img
