name: Build & Push

on:
  push:
    branches: [ main ]


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t hk328/node_app_img
      - run: docker build . -t ghcr.io/himanshukapoor328/node_app_img1
      - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - run: echo "${{secrets.GHCR_PASSWORD}}" | docker login ghcr.io -u ${{secrets.GHCR_USERNAME}} --password-stdin
      - run: docker push hk328/node_app_img
      - run: docker push ghcr.io/himanshukapoor328/node_app_img1
